import path from 'node:path';
import { promises as fs } from 'node:fs';
import type { KnowledgeStore } from '../knowledge/store.js';
import type { LLMProvider } from '../evaluation/provider.js';
import { summarizeKnowledge } from '../knowledge/summarize.js';

// Two-way sync via a dedicated, never-overwritten inbox folder. The operator
// drops or writes notes in `obsidian/_Inbox/` (from inside Obsidian); ADAMAS
// imports each into the Knowledge base, then moves the file to `_Inbox/Imported/`
// so it is never re-imported and the regenerated vault never clobbers it.

export const RESERVED_INBOX = '_Inbox';
const IMPORTED = 'Imported';

const INBOX_README = `# Obsidian → ADAMAS inbox

Write or drop notes **in this folder** (\`.md\` / \`.txt\`) and ADAMAS will import
them into your Knowledge base — summarized, tagged, and linked — then move the
original into \`Imported/\`. This is the safe write-back path: everything else in
this vault is regenerated by ADAMAS and your edits there would be overwritten,
but this folder is yours.
`;

/** Ensure the inbox folder + its README exist (README written only if missing). */
export async function ensureInbox(outDir: string): Promise<void> {
  const inbox = path.join(outDir, RESERVED_INBOX);
  await fs.mkdir(inbox, { recursive: true });
  const readme = path.join(inbox, 'README.md');
  try {
    await fs.access(readme);
  } catch {
    await fs.writeFile(readme, INBOX_README);
  }
}

function stripFrontmatter(text: string): string {
  return text.startsWith('---\n') ? text.replace(/^---\n[\s\S]*?\n---\n?/, '') : text;
}

function titleFrom(body: string, fileName: string): string {
  const heading = /^#\s+(.+)$/m.exec(body)?.[1]?.trim();
  if (heading) return heading.slice(0, 200);
  return fileName.replace(/\.(md|markdown|txt)$/i, '').replace(/[-_]+/g, ' ').trim() || 'Imported note';
}

export interface InboxImportResult {
  imported: number;
  titles: string[];
}

/**
 * Import every note from `obsidian/_Inbox/` into the Knowledge base, then move
 * the source file into `_Inbox/Imported/`. Idempotent: already-imported files
 * have been moved out, so re-running is safe.
 */
export async function importObsidianInbox(
  deps: { knowledge: KnowledgeStore; provider: LLMProvider },
  outDir: string,
): Promise<InboxImportResult> {
  const inbox = path.join(outDir, RESERVED_INBOX);
  await ensureInbox(outDir);

  const entries = await fs.readdir(inbox, { withFileTypes: true });
  const titles: string[] = [];
  let imported = 0;

  for (const ent of entries) {
    if (!ent.isFile()) continue;
    if (!/\.(md|markdown|txt)$/i.test(ent.name)) continue;
    if (ent.name === 'README.md') continue;

    const filePath = path.join(inbox, ent.name);
    const raw = (await fs.readFile(filePath, 'utf8')).trim();
    if (!raw) continue; // skip empty files

    const body = stripFrontmatter(raw).trim();
    const title = titleFrom(body, ent.name);
    const kn = await summarizeKnowledge(deps.provider, body || title);
    await deps.knowledge.create({
      title: (kn.title || title).slice(0, 300),
      source: 'obsidian',
      type: 'note',
      summary: kn.summary,
      takeaways: kn.takeaways,
      tags: kn.tags,
      excerpt: body.slice(0, 500),
    });
    titles.push(title);
    imported += 1;

    // Move the original into Imported/ (timestamp on collision) so it isn't
    // re-imported and the next export never wipes it.
    const importedDir = path.join(inbox, IMPORTED);
    await fs.mkdir(importedDir, { recursive: true });
    let dest = path.join(importedDir, ent.name);
    try {
      await fs.access(dest);
      dest = path.join(importedDir, `${Date.now()}-${ent.name}`);
    } catch {
      /* no collision */
    }
    await fs.rename(filePath, dest);
  }

  return { imported, titles };
}

/**
 * Polls the Obsidian inbox folder and imports new notes on an interval — the
 * "write-back" half of two-way sync. Serialized, errors logged, timer unref'd,
 * stopped on shutdown.
 */
export class ObsidianInboxWatcher {
  private timer: NodeJS.Timeout | null = null;
  private running = false;

  constructor(
    private readonly deps: { knowledge: KnowledgeStore; provider: LLMProvider },
    private readonly outDir: string,
    private readonly intervalMs = 20_000,
  ) {}

  start(): void {
    this.timer = setInterval(() => void this.runOnce(), this.intervalMs);
    this.timer.unref?.();
  }

  async runOnce(): Promise<InboxImportResult> {
    if (this.running) return { imported: 0, titles: [] };
    this.running = true;
    try {
      return await importObsidianInbox(this.deps, this.outDir);
    } catch (err) {
      console.warn(`[obsidian] inbox import failed: ${(err as Error).message}`);
      return { imported: 0, titles: [] };
    } finally {
      this.running = false;
    }
  }

  stop(): void {
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }
}
