import { useLang } from '../i18n';

// Small inline note placed near AI (Hermes) outputs. AI-generated content can be
// inaccurate, so we surface a consistent, reviewable caveat wherever it appears.
export function AiNote() {
  const { t } = useLang();
  return (
    <p className="muted ai-note" style={{ fontSize: 12, margin: '6px 0' }}>
      {t('✨ Generated by Hermes (AI) — may be inaccurate; review before relying.')}
    </p>
  );
}

// Readiness / valuation caveat. The readiness score is a document-completeness
// heuristic, not financial, investment or legal advice.
export function ReadinessNote() {
  const { t } = useLang();
  return (
    <p className="muted readiness-note" style={{ fontSize: 12, margin: '6px 0' }}>
      {t('This readiness score is a document-completeness heuristic — not a valuation or financial, investment, or legal advice. Figures are user-entered and unaudited.')}
    </p>
  );
}
